
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: Check and integrate data

jobs:
  check:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    # env:
    #   GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    #   R_KEEP_PKG_SOURCE: yes

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          install-r: false

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: gsheet, assertr, DT

      - name: Import data
        run: Rscript -e 'df <- gsheet::gsheet2tbl("https://docs.google.com/spreadsheets/d/1oEp3LAcXLt5frr3dverde1YjwUg1fihVtEXKwaLJ_ns/edit?usp=sharing")'

      - name: Import functions
        run: Rscript -e 'source("check_data.R"); source("check_taxonomy.R")'

      - name: Check data
        run: Rscript -e 'check_data(df)'

      - name: Check taxonomy
        run: Rscript -e 'check_taxonomy(df)'

      - name: Integrate new data in database
        run: Rscript -e 'write.csv(df, "database.csv", append = TRUE)'

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



