
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: Check and integrate data

jobs:
  check:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          install-r: false

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: gsheet, assertr, rgbif, DT

      - name: Check data
        run: Rscript -e 'source("process_data.R")'

      - name: Upload changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Upload checked dataset

      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: website.qmd




